/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

import type { Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";

import type {
  Actor,
  BackendError,
  Login,
  PostAuthRegister201,
  RegisterUserRequest,
  Token,
} from "./schemas";

export type getUsersMeResponse200 = {
  data: Actor;
  status: 200;
};

export type getUsersMeResponse404 = {
  data: BackendError;
  status: 404;
};

export type getUsersMeResponseSuccess = getUsersMeResponse200 & {
  headers: Headers;
};
export type getUsersMeResponseError = getUsersMeResponse404 & {
  headers: Headers;
};

export type getUsersMeResponse =
  | getUsersMeResponseSuccess
  | getUsersMeResponseError;

export const getGetUsersMeUrl = () => {
  return `/users/@me`;
};

export const getUsersMe = async (
  options?: RequestInit,
): Promise<getUsersMeResponse> => {
  const res = await fetch(getGetUsersMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersMeResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUsersMeResponse;
};

export const getGetUsersMeKey = () => [`/users/@me`] as const;

export type GetUsersMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersMe>>
>;

export const useGetUsersMe = <TError = Promise<BackendError>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getUsersMe>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetUsersMeKey() : null));
  const swrFn = () => getUsersMe(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postAuthLoginResponse200 = {
  data: Token;
  status: 200;
};

export type postAuthLoginResponse400 = {
  data: BackendError;
  status: 400;
};

export type postAuthLoginResponse403 = {
  data: BackendError;
  status: 403;
};

export type postAuthLoginResponseSuccess = postAuthLoginResponse200 & {
  headers: Headers;
};
export type postAuthLoginResponseError = (
  | postAuthLoginResponse400
  | postAuthLoginResponse403
) & {
  headers: Headers;
};

export type postAuthLoginResponse =
  | postAuthLoginResponseSuccess
  | postAuthLoginResponseError;

export const getPostAuthLoginUrl = () => {
  return `/auth/login`;
};

export const postAuthLogin = async (
  login: Login,
  options?: RequestInit,
): Promise<postAuthLoginResponse> => {
  const res = await fetch(getPostAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(login),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthLoginResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthLoginResponse;
};

export const getPostAuthLoginMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: Login }) => {
    return postAuthLogin(arg, options);
  };
};
export const getPostAuthLoginMutationKey = () => [`/auth/login`] as const;

export type PostAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;

export const usePostAuthLogin = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    Key,
    Login,
    Awaited<ReturnType<typeof postAuthLogin>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthLoginMutationKey();
  const swrFn = getPostAuthLoginMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postAuthRegisterResponse201 = {
  data: PostAuthRegister201;
  status: 201;
};

export type postAuthRegisterResponse400 = {
  data: BackendError;
  status: 400;
};

export type postAuthRegisterResponse409 = {
  data: BackendError;
  status: 409;
};

export type postAuthRegisterResponse500 = {
  data: BackendError;
  status: 500;
};

export type postAuthRegisterResponseSuccess = postAuthRegisterResponse201 & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (
  | postAuthRegisterResponse400
  | postAuthRegisterResponse409
  | postAuthRegisterResponse500
) & {
  headers: Headers;
};

export type postAuthRegisterResponse =
  | postAuthRegisterResponseSuccess
  | postAuthRegisterResponseError;

export const getPostAuthRegisterUrl = () => {
  return `/auth/register`;
};

export const postAuthRegister = async (
  registerUserRequest: RegisterUserRequest,
  options?: RequestInit,
): Promise<postAuthRegisterResponse> => {
  const res = await fetch(getPostAuthRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerUserRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthRegisterResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthRegisterResponse;
};

export const getPostAuthRegisterMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RegisterUserRequest }) => {
    return postAuthRegister(arg, options);
  };
};
export const getPostAuthRegisterMutationKey = () => [`/auth/register`] as const;

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;

export const usePostAuthRegister = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    Key,
    RegisterUserRequest,
    Awaited<ReturnType<typeof postAuthRegister>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthRegisterMutationKey();
  const swrFn = getPostAuthRegisterMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
