/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";

import type {
  Actor,
  AssignRoleRequest,
  AssignRoleResponse,
  BackendError,
  CreateBranchDto,
  CreateReward,
  GetProductsParams,
  GetV1BranchesBranch200,
  GetV1ProductsParams,
  GetV1Reports200,
  IncomingOrders,
  Login,
  LoginResult,
  OrderHistory,
  PatchOrdersIdClose200,
  PatchOrdersIdReady200,
  PatchV1OrdersIdClose200,
  PatchV1OrdersIdReady200,
  PostAuthRegister201,
  PostProducts201,
  PostProductsBody,
  PostV1Branches201,
  PostV1Products201,
  PostV1ProductsBody,
  PostV1Review201,
  PostV1ReviewBody,
  ProductList,
  RedeemResult,
  RedeemReward,
  RedemptionHistoryItem,
  RegisterUserRequest,
  RewardSchema,
  UpdateReward,
} from "./schemas";

export type getUsersMeResponse200 = {
  data: Actor;
  status: 200;
};

export type getUsersMeResponse404 = {
  data: BackendError;
  status: 404;
};

export type getUsersMeResponseSuccess = getUsersMeResponse200 & {
  headers: Headers;
};
export type getUsersMeResponseError = getUsersMeResponse404 & {
  headers: Headers;
};

export type getUsersMeResponse =
  | getUsersMeResponseSuccess
  | getUsersMeResponseError;

export const getGetUsersMeUrl = () => {
  return `http://localhost:8383/users/@me`;
};

export const getUsersMe = async (
  options?: RequestInit,
): Promise<getUsersMeResponse> => {
  const res = await fetch(getGetUsersMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersMeResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUsersMeResponse;
};

export const getGetUsersMeKey = () =>
  [`http://localhost:8383/users/@me`] as const;

export type GetUsersMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersMe>>
>;

export const useGetUsersMe = <TError = Promise<BackendError>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getUsersMe>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetUsersMeKey() : null));
  const swrFn = () => getUsersMe(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postUsersUserIdRolesResponse200 = {
  data: AssignRoleResponse;
  status: 200;
};

export type postUsersUserIdRolesResponse403 = {
  data: BackendError;
  status: 403;
};

export type postUsersUserIdRolesResponse404 = {
  data: BackendError;
  status: 404;
};

export type postUsersUserIdRolesResponseSuccess =
  postUsersUserIdRolesResponse200 & {
    headers: Headers;
  };
export type postUsersUserIdRolesResponseError = (
  | postUsersUserIdRolesResponse403
  | postUsersUserIdRolesResponse404
) & {
  headers: Headers;
};

export type postUsersUserIdRolesResponse =
  | postUsersUserIdRolesResponseSuccess
  | postUsersUserIdRolesResponseError;

export const getPostUsersUserIdRolesUrl = (userId: string) => {
  return `http://localhost:8383/users/${userId}/roles`;
};

export const postUsersUserIdRoles = async (
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: RequestInit,
): Promise<postUsersUserIdRolesResponse> => {
  const res = await fetch(getPostUsersUserIdRolesUrl(userId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(assignRoleRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUsersUserIdRolesResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postUsersUserIdRolesResponse;
};

export const getPostUsersUserIdRolesMutationFetcher = (
  userId: string,
  options?: RequestInit,
) => {
  return (_: Key, { arg }: { arg: AssignRoleRequest }) => {
    return postUsersUserIdRoles(userId, arg, options);
  };
};
export const getPostUsersUserIdRolesMutationKey = (userId: string) =>
  [`http://localhost:8383/users/${userId}/roles`] as const;

export type PostUsersUserIdRolesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUsersUserIdRoles>>
>;

export const usePostUsersUserIdRoles = <TError = Promise<BackendError>>(
  userId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postUsersUserIdRoles>>,
      TError,
      Key,
      AssignRoleRequest,
      Awaited<ReturnType<typeof postUsersUserIdRoles>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getPostUsersUserIdRolesMutationKey(userId);
  const swrFn = getPostUsersUserIdRolesMutationFetcher(userId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type deleteUsersUserIdRolesRoleNameResponse200 = {
  data: AssignRoleResponse;
  status: 200;
};

export type deleteUsersUserIdRolesRoleNameResponse403 = {
  data: BackendError;
  status: 403;
};

export type deleteUsersUserIdRolesRoleNameResponse404 = {
  data: BackendError;
  status: 404;
};

export type deleteUsersUserIdRolesRoleNameResponseSuccess =
  deleteUsersUserIdRolesRoleNameResponse200 & {
    headers: Headers;
  };
export type deleteUsersUserIdRolesRoleNameResponseError = (
  | deleteUsersUserIdRolesRoleNameResponse403
  | deleteUsersUserIdRolesRoleNameResponse404
) & {
  headers: Headers;
};

export type deleteUsersUserIdRolesRoleNameResponse =
  | deleteUsersUserIdRolesRoleNameResponseSuccess
  | deleteUsersUserIdRolesRoleNameResponseError;

export const getDeleteUsersUserIdRolesRoleNameUrl = (
  userId: string,
  roleName: string,
) => {
  return `http://localhost:8383/users/${userId}/roles/${roleName}`;
};

export const deleteUsersUserIdRolesRoleName = async (
  userId: string,
  roleName: string,
  options?: RequestInit,
): Promise<deleteUsersUserIdRolesRoleNameResponse> => {
  const res = await fetch(
    getDeleteUsersUserIdRolesRoleNameUrl(userId, roleName),
    {
      ...options,
      method: "DELETE",
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUsersUserIdRolesRoleNameResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteUsersUserIdRolesRoleNameResponse;
};

export const getDeleteUsersUserIdRolesRoleNameMutationFetcher = (
  userId: string,
  roleName: string,
  options?: RequestInit,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteUsersUserIdRolesRoleName(userId, roleName, options);
  };
};
export const getDeleteUsersUserIdRolesRoleNameMutationKey = (
  userId: string,
  roleName: string,
) => [`http://localhost:8383/users/${userId}/roles/${roleName}`] as const;

export type DeleteUsersUserIdRolesRoleNameMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUsersUserIdRolesRoleName>>
>;

export const useDeleteUsersUserIdRolesRoleName = <
  TError = Promise<BackendError>,
>(
  userId: string,
  roleName: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteUsersUserIdRolesRoleName>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteUsersUserIdRolesRoleName>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ??
    getDeleteUsersUserIdRolesRoleNameMutationKey(userId, roleName);
  const swrFn = getDeleteUsersUserIdRolesRoleNameMutationFetcher(
    userId,
    roleName,
    fetchOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getProductsResponse200 = {
  data: ProductList;
  status: 200;
};

export type getProductsResponse400 = {
  data: BackendError;
  status: 400;
};

export type getProductsResponseSuccess = getProductsResponse200 & {
  headers: Headers;
};
export type getProductsResponseError = getProductsResponse400 & {
  headers: Headers;
};

export type getProductsResponse =
  | getProductsResponseSuccess
  | getProductsResponseError;

export const getGetProductsUrl = (params?: GetProductsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:8383/products?${stringifiedParams}`
    : `http://localhost:8383/products`;
};

export const getProducts = async (
  params?: GetProductsParams,
  options?: RequestInit,
): Promise<getProductsResponse> => {
  const res = await fetch(getGetProductsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProductsResponse;
};

export const getGetProductsKey = (params?: GetProductsParams) =>
  [`http://localhost:8383/products`, ...(params ? [params] : [])] as const;

export type GetProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProducts>>
>;

export const useGetProducts = <TError = Promise<BackendError>>(
  params?: GetProductsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getProducts>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetProductsKey(params) : null));
  const swrFn = () => getProducts(params, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postProductsResponse201 = {
  data: PostProducts201;
  status: 201;
};

export type postProductsResponse409 = {
  data: BackendError;
  status: 409;
};

export type postProductsResponse500 = {
  data: BackendError;
  status: 500;
};

export type postProductsResponseSuccess = postProductsResponse201 & {
  headers: Headers;
};
export type postProductsResponseError = (
  | postProductsResponse409
  | postProductsResponse500
) & {
  headers: Headers;
};

export type postProductsResponse =
  | postProductsResponseSuccess
  | postProductsResponseError;

export const getPostProductsUrl = () => {
  return `http://localhost:8383/products`;
};

export const postProducts = async (
  postProductsBody: PostProductsBody,
  options?: RequestInit,
): Promise<postProductsResponse> => {
  const res = await fetch(getPostProductsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postProductsBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postProductsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postProductsResponse;
};

export const getPostProductsMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: PostProductsBody }) => {
    return postProducts(arg, options);
  };
};
export const getPostProductsMutationKey = () =>
  [`http://localhost:8383/products`] as const;

export type PostProductsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProducts>>
>;

export const usePostProducts = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postProducts>>,
    TError,
    Key,
    PostProductsBody,
    Awaited<ReturnType<typeof postProducts>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostProductsMutationKey();
  const swrFn = getPostProductsMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getOrdersHistoryResponse200 = {
  data: OrderHistory;
  status: 200;
};

export type getOrdersHistoryResponse500 = {
  data: BackendError;
  status: 500;
};

export type getOrdersHistoryResponseSuccess = getOrdersHistoryResponse200 & {
  headers: Headers;
};
export type getOrdersHistoryResponseError = getOrdersHistoryResponse500 & {
  headers: Headers;
};

export type getOrdersHistoryResponse =
  | getOrdersHistoryResponseSuccess
  | getOrdersHistoryResponseError;

export const getGetOrdersHistoryUrl = () => {
  return `http://localhost:8383/orders/history`;
};

export const getOrdersHistory = async (
  options?: RequestInit,
): Promise<getOrdersHistoryResponse> => {
  const res = await fetch(getGetOrdersHistoryUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrdersHistoryResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getOrdersHistoryResponse;
};

export const getGetOrdersHistoryKey = () =>
  [`http://localhost:8383/orders/history`] as const;

export type GetOrdersHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrdersHistory>>
>;

export const useGetOrdersHistory = <TError = Promise<BackendError>>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getOrdersHistory>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetOrdersHistoryKey() : null));
  const swrFn = () => getOrdersHistory(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type patchOrdersIdCloseResponse200 = {
  data: PatchOrdersIdClose200;
  status: 200;
};

export type patchOrdersIdCloseResponse404 = {
  data: BackendError;
  status: 404;
};

export type patchOrdersIdCloseResponse409 = {
  data: BackendError;
  status: 409;
};

export type patchOrdersIdCloseResponse500 = {
  data: BackendError;
  status: 500;
};

export type patchOrdersIdCloseResponseSuccess =
  patchOrdersIdCloseResponse200 & {
    headers: Headers;
  };
export type patchOrdersIdCloseResponseError = (
  | patchOrdersIdCloseResponse404
  | patchOrdersIdCloseResponse409
  | patchOrdersIdCloseResponse500
) & {
  headers: Headers;
};

export type patchOrdersIdCloseResponse =
  | patchOrdersIdCloseResponseSuccess
  | patchOrdersIdCloseResponseError;

export const getPatchOrdersIdCloseUrl = () => {
  return `http://localhost:8383/orders/:id/close`;
};

export const patchOrdersIdClose = async (
  options?: RequestInit,
): Promise<patchOrdersIdCloseResponse> => {
  const res = await fetch(getPatchOrdersIdCloseUrl(), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchOrdersIdCloseResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchOrdersIdCloseResponse;
};

export const getPatchOrdersIdCloseMutationFetcher = (options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return patchOrdersIdClose(options);
  };
};
export const getPatchOrdersIdCloseMutationKey = () =>
  [`http://localhost:8383/orders/:id/close`] as const;

export type PatchOrdersIdCloseMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchOrdersIdClose>>
>;

export const usePatchOrdersIdClose = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof patchOrdersIdClose>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof patchOrdersIdClose>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPatchOrdersIdCloseMutationKey();
  const swrFn = getPatchOrdersIdCloseMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type patchOrdersIdReadyResponse200 = {
  data: PatchOrdersIdReady200;
  status: 200;
};

export type patchOrdersIdReadyResponse404 = {
  data: BackendError;
  status: 404;
};

export type patchOrdersIdReadyResponse409 = {
  data: BackendError;
  status: 409;
};

export type patchOrdersIdReadyResponse500 = {
  data: BackendError;
  status: 500;
};

export type patchOrdersIdReadyResponseSuccess =
  patchOrdersIdReadyResponse200 & {
    headers: Headers;
  };
export type patchOrdersIdReadyResponseError = (
  | patchOrdersIdReadyResponse404
  | patchOrdersIdReadyResponse409
  | patchOrdersIdReadyResponse500
) & {
  headers: Headers;
};

export type patchOrdersIdReadyResponse =
  | patchOrdersIdReadyResponseSuccess
  | patchOrdersIdReadyResponseError;

export const getPatchOrdersIdReadyUrl = () => {
  return `http://localhost:8383/orders/:id/ready`;
};

export const patchOrdersIdReady = async (
  options?: RequestInit,
): Promise<patchOrdersIdReadyResponse> => {
  const res = await fetch(getPatchOrdersIdReadyUrl(), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchOrdersIdReadyResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchOrdersIdReadyResponse;
};

export const getPatchOrdersIdReadyMutationFetcher = (options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return patchOrdersIdReady(options);
  };
};
export const getPatchOrdersIdReadyMutationKey = () =>
  [`http://localhost:8383/orders/:id/ready`] as const;

export type PatchOrdersIdReadyMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchOrdersIdReady>>
>;

export const usePatchOrdersIdReady = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof patchOrdersIdReady>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof patchOrdersIdReady>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPatchOrdersIdReadyMutationKey();
  const swrFn = getPatchOrdersIdReadyMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getOrdersIncomingResponse200 = {
  data: IncomingOrders;
  status: 200;
};

export type getOrdersIncomingResponse500 = {
  data: BackendError;
  status: 500;
};

export type getOrdersIncomingResponseSuccess = getOrdersIncomingResponse200 & {
  headers: Headers;
};
export type getOrdersIncomingResponseError = getOrdersIncomingResponse500 & {
  headers: Headers;
};

export type getOrdersIncomingResponse =
  | getOrdersIncomingResponseSuccess
  | getOrdersIncomingResponseError;

export const getGetOrdersIncomingUrl = () => {
  return `http://localhost:8383/orders/incoming`;
};

export const getOrdersIncoming = async (
  options?: RequestInit,
): Promise<getOrdersIncomingResponse> => {
  const res = await fetch(getGetOrdersIncomingUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrdersIncomingResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getOrdersIncomingResponse;
};

export const getGetOrdersIncomingKey = () =>
  [`http://localhost:8383/orders/incoming`] as const;

export type GetOrdersIncomingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrdersIncoming>>
>;

export const useGetOrdersIncoming = <TError = Promise<BackendError>>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getOrdersIncoming>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetOrdersIncomingKey() : null));
  const swrFn = () => getOrdersIncoming(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postAuthLoginResponse200 = {
  data: LoginResult;
  status: 200;
};

export type postAuthLoginResponse400 = {
  data: BackendError;
  status: 400;
};

export type postAuthLoginResponse403 = {
  data: BackendError;
  status: 403;
};

export type postAuthLoginResponseSuccess = postAuthLoginResponse200 & {
  headers: Headers;
};
export type postAuthLoginResponseError = (
  | postAuthLoginResponse400
  | postAuthLoginResponse403
) & {
  headers: Headers;
};

export type postAuthLoginResponse =
  | postAuthLoginResponseSuccess
  | postAuthLoginResponseError;

export const getPostAuthLoginUrl = () => {
  return `http://localhost:8383/auth/login`;
};

export const postAuthLogin = async (
  login: Login,
  options?: RequestInit,
): Promise<postAuthLoginResponse> => {
  const res = await fetch(getPostAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(login),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthLoginResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthLoginResponse;
};

export const getPostAuthLoginMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: Login }) => {
    return postAuthLogin(arg, options);
  };
};
export const getPostAuthLoginMutationKey = () =>
  [`http://localhost:8383/auth/login`] as const;

export type PostAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;

export const usePostAuthLogin = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    Key,
    Login,
    Awaited<ReturnType<typeof postAuthLogin>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthLoginMutationKey();
  const swrFn = getPostAuthLoginMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postAuthRegisterResponse201 = {
  data: PostAuthRegister201;
  status: 201;
};

export type postAuthRegisterResponse400 = {
  data: BackendError;
  status: 400;
};

export type postAuthRegisterResponse409 = {
  data: BackendError;
  status: 409;
};

export type postAuthRegisterResponse500 = {
  data: BackendError;
  status: 500;
};

export type postAuthRegisterResponseSuccess = postAuthRegisterResponse201 & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (
  | postAuthRegisterResponse400
  | postAuthRegisterResponse409
  | postAuthRegisterResponse500
) & {
  headers: Headers;
};

export type postAuthRegisterResponse =
  | postAuthRegisterResponseSuccess
  | postAuthRegisterResponseError;

export const getPostAuthRegisterUrl = () => {
  return `http://localhost:8383/auth/register`;
};

export const postAuthRegister = async (
  registerUserRequest: RegisterUserRequest,
  options?: RequestInit,
): Promise<postAuthRegisterResponse> => {
  const res = await fetch(getPostAuthRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerUserRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthRegisterResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthRegisterResponse;
};

export const getPostAuthRegisterMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RegisterUserRequest }) => {
    return postAuthRegister(arg, options);
  };
};
export const getPostAuthRegisterMutationKey = () =>
  [`http://localhost:8383/auth/register`] as const;

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;

export const usePostAuthRegister = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    Key,
    RegisterUserRequest,
    Awaited<ReturnType<typeof postAuthRegister>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthRegisterMutationKey();
  const swrFn = getPostAuthRegisterMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getV1UsersMeResponse200 = {
  data: Actor;
  status: 200;
};

export type getV1UsersMeResponse404 = {
  data: BackendError;
  status: 404;
};

export type getV1UsersMeResponseSuccess = getV1UsersMeResponse200 & {
  headers: Headers;
};
export type getV1UsersMeResponseError = getV1UsersMeResponse404 & {
  headers: Headers;
};

export type getV1UsersMeResponse =
  | getV1UsersMeResponseSuccess
  | getV1UsersMeResponseError;

export const getGetV1UsersMeUrl = () => {
  return `http://localhost:8383/v1/users/@me`;
};

export const getV1UsersMe = async (
  options?: RequestInit,
): Promise<getV1UsersMeResponse> => {
  const res = await fetch(getGetV1UsersMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1UsersMeResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1UsersMeResponse;
};

export const getGetV1UsersMeKey = () =>
  [`http://localhost:8383/v1/users/@me`] as const;

export type GetV1UsersMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1UsersMe>>
>;

export const useGetV1UsersMe = <TError = Promise<BackendError>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getV1UsersMe>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetV1UsersMeKey() : null));
  const swrFn = () => getV1UsersMe(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postV1UsersUserIdRolesResponse200 = {
  data: AssignRoleResponse;
  status: 200;
};

export type postV1UsersUserIdRolesResponse403 = {
  data: BackendError;
  status: 403;
};

export type postV1UsersUserIdRolesResponse404 = {
  data: BackendError;
  status: 404;
};

export type postV1UsersUserIdRolesResponseSuccess =
  postV1UsersUserIdRolesResponse200 & {
    headers: Headers;
  };
export type postV1UsersUserIdRolesResponseError = (
  | postV1UsersUserIdRolesResponse403
  | postV1UsersUserIdRolesResponse404
) & {
  headers: Headers;
};

export type postV1UsersUserIdRolesResponse =
  | postV1UsersUserIdRolesResponseSuccess
  | postV1UsersUserIdRolesResponseError;

export const getPostV1UsersUserIdRolesUrl = (userId: string) => {
  return `http://localhost:8383/v1/users/${userId}/roles`;
};

export const postV1UsersUserIdRoles = async (
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: RequestInit,
): Promise<postV1UsersUserIdRolesResponse> => {
  const res = await fetch(getPostV1UsersUserIdRolesUrl(userId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(assignRoleRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1UsersUserIdRolesResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postV1UsersUserIdRolesResponse;
};

export const getPostV1UsersUserIdRolesMutationFetcher = (
  userId: string,
  options?: RequestInit,
) => {
  return (_: Key, { arg }: { arg: AssignRoleRequest }) => {
    return postV1UsersUserIdRoles(userId, arg, options);
  };
};
export const getPostV1UsersUserIdRolesMutationKey = (userId: string) =>
  [`http://localhost:8383/v1/users/${userId}/roles`] as const;

export type PostV1UsersUserIdRolesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1UsersUserIdRoles>>
>;

export const usePostV1UsersUserIdRoles = <TError = Promise<BackendError>>(
  userId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postV1UsersUserIdRoles>>,
      TError,
      Key,
      AssignRoleRequest,
      Awaited<ReturnType<typeof postV1UsersUserIdRoles>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getPostV1UsersUserIdRolesMutationKey(userId);
  const swrFn = getPostV1UsersUserIdRolesMutationFetcher(userId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type deleteV1UsersUserIdRolesRoleNameResponse200 = {
  data: AssignRoleResponse;
  status: 200;
};

export type deleteV1UsersUserIdRolesRoleNameResponse403 = {
  data: BackendError;
  status: 403;
};

export type deleteV1UsersUserIdRolesRoleNameResponse404 = {
  data: BackendError;
  status: 404;
};

export type deleteV1UsersUserIdRolesRoleNameResponseSuccess =
  deleteV1UsersUserIdRolesRoleNameResponse200 & {
    headers: Headers;
  };
export type deleteV1UsersUserIdRolesRoleNameResponseError = (
  | deleteV1UsersUserIdRolesRoleNameResponse403
  | deleteV1UsersUserIdRolesRoleNameResponse404
) & {
  headers: Headers;
};

export type deleteV1UsersUserIdRolesRoleNameResponse =
  | deleteV1UsersUserIdRolesRoleNameResponseSuccess
  | deleteV1UsersUserIdRolesRoleNameResponseError;

export const getDeleteV1UsersUserIdRolesRoleNameUrl = (
  userId: string,
  roleName: string,
) => {
  return `http://localhost:8383/v1/users/${userId}/roles/${roleName}`;
};

export const deleteV1UsersUserIdRolesRoleName = async (
  userId: string,
  roleName: string,
  options?: RequestInit,
): Promise<deleteV1UsersUserIdRolesRoleNameResponse> => {
  const res = await fetch(
    getDeleteV1UsersUserIdRolesRoleNameUrl(userId, roleName),
    {
      ...options,
      method: "DELETE",
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteV1UsersUserIdRolesRoleNameResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteV1UsersUserIdRolesRoleNameResponse;
};

export const getDeleteV1UsersUserIdRolesRoleNameMutationFetcher = (
  userId: string,
  roleName: string,
  options?: RequestInit,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteV1UsersUserIdRolesRoleName(userId, roleName, options);
  };
};
export const getDeleteV1UsersUserIdRolesRoleNameMutationKey = (
  userId: string,
  roleName: string,
) => [`http://localhost:8383/v1/users/${userId}/roles/${roleName}`] as const;

export type DeleteV1UsersUserIdRolesRoleNameMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteV1UsersUserIdRolesRoleName>>
>;

export const useDeleteV1UsersUserIdRolesRoleName = <
  TError = Promise<BackendError>,
>(
  userId: string,
  roleName: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteV1UsersUserIdRolesRoleName>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteV1UsersUserIdRolesRoleName>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ??
    getDeleteV1UsersUserIdRolesRoleNameMutationKey(userId, roleName);
  const swrFn = getDeleteV1UsersUserIdRolesRoleNameMutationFetcher(
    userId,
    roleName,
    fetchOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getV1ProductsResponse200 = {
  data: ProductList;
  status: 200;
};

export type getV1ProductsResponse400 = {
  data: BackendError;
  status: 400;
};

export type getV1ProductsResponseSuccess = getV1ProductsResponse200 & {
  headers: Headers;
};
export type getV1ProductsResponseError = getV1ProductsResponse400 & {
  headers: Headers;
};

export type getV1ProductsResponse =
  | getV1ProductsResponseSuccess
  | getV1ProductsResponseError;

export const getGetV1ProductsUrl = (params?: GetV1ProductsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:8383/v1/products?${stringifiedParams}`
    : `http://localhost:8383/v1/products`;
};

export const getV1Products = async (
  params?: GetV1ProductsParams,
  options?: RequestInit,
): Promise<getV1ProductsResponse> => {
  const res = await fetch(getGetV1ProductsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1ProductsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1ProductsResponse;
};

export const getGetV1ProductsKey = (params?: GetV1ProductsParams) =>
  [`http://localhost:8383/v1/products`, ...(params ? [params] : [])] as const;

export type GetV1ProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1Products>>
>;

export const useGetV1Products = <TError = Promise<BackendError>>(
  params?: GetV1ProductsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getV1Products>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetV1ProductsKey(params) : null));
  const swrFn = () => getV1Products(params, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postV1ProductsResponse201 = {
  data: PostV1Products201;
  status: 201;
};

export type postV1ProductsResponse409 = {
  data: BackendError;
  status: 409;
};

export type postV1ProductsResponse500 = {
  data: BackendError;
  status: 500;
};

export type postV1ProductsResponseSuccess = postV1ProductsResponse201 & {
  headers: Headers;
};
export type postV1ProductsResponseError = (
  | postV1ProductsResponse409
  | postV1ProductsResponse500
) & {
  headers: Headers;
};

export type postV1ProductsResponse =
  | postV1ProductsResponseSuccess
  | postV1ProductsResponseError;

export const getPostV1ProductsUrl = () => {
  return `http://localhost:8383/v1/products`;
};

export const postV1Products = async (
  postV1ProductsBody: PostV1ProductsBody,
  options?: RequestInit,
): Promise<postV1ProductsResponse> => {
  const res = await fetch(getPostV1ProductsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postV1ProductsBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1ProductsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postV1ProductsResponse;
};

export const getPostV1ProductsMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: PostV1ProductsBody }) => {
    return postV1Products(arg, options);
  };
};
export const getPostV1ProductsMutationKey = () =>
  [`http://localhost:8383/v1/products`] as const;

export type PostV1ProductsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1Products>>
>;

export const usePostV1Products = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postV1Products>>,
    TError,
    Key,
    PostV1ProductsBody,
    Awaited<ReturnType<typeof postV1Products>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostV1ProductsMutationKey();
  const swrFn = getPostV1ProductsMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getV1OrdersHistoryResponse200 = {
  data: OrderHistory;
  status: 200;
};

export type getV1OrdersHistoryResponse500 = {
  data: BackendError;
  status: 500;
};

export type getV1OrdersHistoryResponseSuccess =
  getV1OrdersHistoryResponse200 & {
    headers: Headers;
  };
export type getV1OrdersHistoryResponseError = getV1OrdersHistoryResponse500 & {
  headers: Headers;
};

export type getV1OrdersHistoryResponse =
  | getV1OrdersHistoryResponseSuccess
  | getV1OrdersHistoryResponseError;

export const getGetV1OrdersHistoryUrl = () => {
  return `http://localhost:8383/v1/orders/history`;
};

export const getV1OrdersHistory = async (
  options?: RequestInit,
): Promise<getV1OrdersHistoryResponse> => {
  const res = await fetch(getGetV1OrdersHistoryUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1OrdersHistoryResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1OrdersHistoryResponse;
};

export const getGetV1OrdersHistoryKey = () =>
  [`http://localhost:8383/v1/orders/history`] as const;

export type GetV1OrdersHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1OrdersHistory>>
>;

export const useGetV1OrdersHistory = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getV1OrdersHistory>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetV1OrdersHistoryKey() : null));
  const swrFn = () => getV1OrdersHistory(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type patchV1OrdersIdCloseResponse200 = {
  data: PatchV1OrdersIdClose200;
  status: 200;
};

export type patchV1OrdersIdCloseResponse404 = {
  data: BackendError;
  status: 404;
};

export type patchV1OrdersIdCloseResponse409 = {
  data: BackendError;
  status: 409;
};

export type patchV1OrdersIdCloseResponse500 = {
  data: BackendError;
  status: 500;
};

export type patchV1OrdersIdCloseResponseSuccess =
  patchV1OrdersIdCloseResponse200 & {
    headers: Headers;
  };
export type patchV1OrdersIdCloseResponseError = (
  | patchV1OrdersIdCloseResponse404
  | patchV1OrdersIdCloseResponse409
  | patchV1OrdersIdCloseResponse500
) & {
  headers: Headers;
};

export type patchV1OrdersIdCloseResponse =
  | patchV1OrdersIdCloseResponseSuccess
  | patchV1OrdersIdCloseResponseError;

export const getPatchV1OrdersIdCloseUrl = () => {
  return `http://localhost:8383/v1/orders/:id/close`;
};

export const patchV1OrdersIdClose = async (
  options?: RequestInit,
): Promise<patchV1OrdersIdCloseResponse> => {
  const res = await fetch(getPatchV1OrdersIdCloseUrl(), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchV1OrdersIdCloseResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchV1OrdersIdCloseResponse;
};

export const getPatchV1OrdersIdCloseMutationFetcher = (
  options?: RequestInit,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return patchV1OrdersIdClose(options);
  };
};
export const getPatchV1OrdersIdCloseMutationKey = () =>
  [`http://localhost:8383/v1/orders/:id/close`] as const;

export type PatchV1OrdersIdCloseMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchV1OrdersIdClose>>
>;

export const usePatchV1OrdersIdClose = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof patchV1OrdersIdClose>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof patchV1OrdersIdClose>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPatchV1OrdersIdCloseMutationKey();
  const swrFn = getPatchV1OrdersIdCloseMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type patchV1OrdersIdReadyResponse200 = {
  data: PatchV1OrdersIdReady200;
  status: 200;
};

export type patchV1OrdersIdReadyResponse404 = {
  data: BackendError;
  status: 404;
};

export type patchV1OrdersIdReadyResponse409 = {
  data: BackendError;
  status: 409;
};

export type patchV1OrdersIdReadyResponse500 = {
  data: BackendError;
  status: 500;
};

export type patchV1OrdersIdReadyResponseSuccess =
  patchV1OrdersIdReadyResponse200 & {
    headers: Headers;
  };
export type patchV1OrdersIdReadyResponseError = (
  | patchV1OrdersIdReadyResponse404
  | patchV1OrdersIdReadyResponse409
  | patchV1OrdersIdReadyResponse500
) & {
  headers: Headers;
};

export type patchV1OrdersIdReadyResponse =
  | patchV1OrdersIdReadyResponseSuccess
  | patchV1OrdersIdReadyResponseError;

export const getPatchV1OrdersIdReadyUrl = () => {
  return `http://localhost:8383/v1/orders/:id/ready`;
};

export const patchV1OrdersIdReady = async (
  options?: RequestInit,
): Promise<patchV1OrdersIdReadyResponse> => {
  const res = await fetch(getPatchV1OrdersIdReadyUrl(), {
    ...options,
    method: "PATCH",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchV1OrdersIdReadyResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchV1OrdersIdReadyResponse;
};

export const getPatchV1OrdersIdReadyMutationFetcher = (
  options?: RequestInit,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return patchV1OrdersIdReady(options);
  };
};
export const getPatchV1OrdersIdReadyMutationKey = () =>
  [`http://localhost:8383/v1/orders/:id/ready`] as const;

export type PatchV1OrdersIdReadyMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchV1OrdersIdReady>>
>;

export const usePatchV1OrdersIdReady = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof patchV1OrdersIdReady>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof patchV1OrdersIdReady>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPatchV1OrdersIdReadyMutationKey();
  const swrFn = getPatchV1OrdersIdReadyMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getV1OrdersIncomingResponse200 = {
  data: IncomingOrders;
  status: 200;
};

export type getV1OrdersIncomingResponse500 = {
  data: BackendError;
  status: 500;
};

export type getV1OrdersIncomingResponseSuccess =
  getV1OrdersIncomingResponse200 & {
    headers: Headers;
  };
export type getV1OrdersIncomingResponseError =
  getV1OrdersIncomingResponse500 & {
    headers: Headers;
  };

export type getV1OrdersIncomingResponse =
  | getV1OrdersIncomingResponseSuccess
  | getV1OrdersIncomingResponseError;

export const getGetV1OrdersIncomingUrl = () => {
  return `http://localhost:8383/v1/orders/incoming`;
};

export const getV1OrdersIncoming = async (
  options?: RequestInit,
): Promise<getV1OrdersIncomingResponse> => {
  const res = await fetch(getGetV1OrdersIncomingUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1OrdersIncomingResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1OrdersIncomingResponse;
};

export const getGetV1OrdersIncomingKey = () =>
  [`http://localhost:8383/v1/orders/incoming`] as const;

export type GetV1OrdersIncomingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1OrdersIncoming>>
>;

export const useGetV1OrdersIncoming = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getV1OrdersIncoming>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetV1OrdersIncomingKey() : null));
  const swrFn = () => getV1OrdersIncoming(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type getV1ReportsResponse200 = {
  data: GetV1Reports200;
  status: 200;
};

export type getV1ReportsResponse500 = {
  data: BackendError;
  status: 500;
};

export type getV1ReportsResponseSuccess = getV1ReportsResponse200 & {
  headers: Headers;
};
export type getV1ReportsResponseError = getV1ReportsResponse500 & {
  headers: Headers;
};

export type getV1ReportsResponse =
  | getV1ReportsResponseSuccess
  | getV1ReportsResponseError;

export const getGetV1ReportsUrl = () => {
  return `http://localhost:8383/v1/reports`;
};

export const getV1Reports = async (
  options?: RequestInit,
): Promise<getV1ReportsResponse> => {
  const res = await fetch(getGetV1ReportsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1ReportsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1ReportsResponse;
};

export const getGetV1ReportsKey = () =>
  [`http://localhost:8383/v1/reports`] as const;

export type GetV1ReportsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1Reports>>
>;

export const useGetV1Reports = <TError = Promise<BackendError>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getV1Reports>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetV1ReportsKey() : null));
  const swrFn = () => getV1Reports(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postV1RewardsResponse201 = {
  data: RewardSchema;
  status: 201;
};

export type postV1RewardsResponse400 = {
  data: BackendError;
  status: 400;
};

export type postV1RewardsResponseSuccess = postV1RewardsResponse201 & {
  headers: Headers;
};
export type postV1RewardsResponseError = postV1RewardsResponse400 & {
  headers: Headers;
};

export type postV1RewardsResponse =
  | postV1RewardsResponseSuccess
  | postV1RewardsResponseError;

export const getPostV1RewardsUrl = () => {
  return `http://localhost:8383/v1/rewards`;
};

export const postV1Rewards = async (
  createReward: CreateReward,
  options?: RequestInit,
): Promise<postV1RewardsResponse> => {
  const res = await fetch(getPostV1RewardsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createReward),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1RewardsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postV1RewardsResponse;
};

export const getPostV1RewardsMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateReward }) => {
    return postV1Rewards(arg, options);
  };
};
export const getPostV1RewardsMutationKey = () =>
  [`http://localhost:8383/v1/rewards`] as const;

export type PostV1RewardsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1Rewards>>
>;

export const usePostV1Rewards = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postV1Rewards>>,
    TError,
    Key,
    CreateReward,
    Awaited<ReturnType<typeof postV1Rewards>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostV1RewardsMutationKey();
  const swrFn = getPostV1RewardsMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getV1RewardsResponse200 = {
  data: RewardSchema[];
  status: 200;
};

export type getV1RewardsResponseSuccess = getV1RewardsResponse200 & {
  headers: Headers;
};

export type getV1RewardsResponse = getV1RewardsResponseSuccess;

export const getGetV1RewardsUrl = () => {
  return `http://localhost:8383/v1/rewards`;
};

export const getV1Rewards = async (
  options?: RequestInit,
): Promise<getV1RewardsResponse> => {
  const res = await fetch(getGetV1RewardsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1RewardsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1RewardsResponse;
};

export const getGetV1RewardsKey = () =>
  [`http://localhost:8383/v1/rewards`] as const;

export type GetV1RewardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1Rewards>>
>;

export const useGetV1Rewards = <TError = Promise<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getV1Rewards>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetV1RewardsKey() : null));
  const swrFn = () => getV1Rewards(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type getV1RewardsHistoryResponse200 = {
  data: RedemptionHistoryItem[];
  status: 200;
};

export type getV1RewardsHistoryResponseSuccess =
  getV1RewardsHistoryResponse200 & {
    headers: Headers;
  };

export type getV1RewardsHistoryResponse = getV1RewardsHistoryResponseSuccess;

export const getGetV1RewardsHistoryUrl = () => {
  return `http://localhost:8383/v1/rewards/history`;
};

export const getV1RewardsHistory = async (
  options?: RequestInit,
): Promise<getV1RewardsHistoryResponse> => {
  const res = await fetch(getGetV1RewardsHistoryUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1RewardsHistoryResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1RewardsHistoryResponse;
};

export const getGetV1RewardsHistoryKey = () =>
  [`http://localhost:8383/v1/rewards/history`] as const;

export type GetV1RewardsHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1RewardsHistory>>
>;

export const useGetV1RewardsHistory = <TError = Promise<unknown>>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getV1RewardsHistory>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetV1RewardsHistoryKey() : null));
  const swrFn = () => getV1RewardsHistory(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export type postV1RewardsRedeemResponse200 = {
  data: RedeemResult;
  status: 200;
};

export type postV1RewardsRedeemResponse400 = {
  data: BackendError;
  status: 400;
};

export type postV1RewardsRedeemResponseSuccess =
  postV1RewardsRedeemResponse200 & {
    headers: Headers;
  };
export type postV1RewardsRedeemResponseError =
  postV1RewardsRedeemResponse400 & {
    headers: Headers;
  };

export type postV1RewardsRedeemResponse =
  | postV1RewardsRedeemResponseSuccess
  | postV1RewardsRedeemResponseError;

export const getPostV1RewardsRedeemUrl = () => {
  return `http://localhost:8383/v1/rewards/redeem`;
};

export const postV1RewardsRedeem = async (
  redeemReward: RedeemReward,
  options?: RequestInit,
): Promise<postV1RewardsRedeemResponse> => {
  const res = await fetch(getPostV1RewardsRedeemUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(redeemReward),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1RewardsRedeemResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postV1RewardsRedeemResponse;
};

export const getPostV1RewardsRedeemMutationFetcher = (
  options?: RequestInit,
) => {
  return (_: Key, { arg }: { arg: RedeemReward }) => {
    return postV1RewardsRedeem(arg, options);
  };
};
export const getPostV1RewardsRedeemMutationKey = () =>
  [`http://localhost:8383/v1/rewards/redeem`] as const;

export type PostV1RewardsRedeemMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1RewardsRedeem>>
>;

export const usePostV1RewardsRedeem = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postV1RewardsRedeem>>,
    TError,
    Key,
    RedeemReward,
    Awaited<ReturnType<typeof postV1RewardsRedeem>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostV1RewardsRedeemMutationKey();
  const swrFn = getPostV1RewardsRedeemMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type deleteV1RewardsRewardIdResponse204 = {
  data: undefined;
  status: 204;
};

export type deleteV1RewardsRewardIdResponse400 = {
  data: BackendError;
  status: 400;
};

export type deleteV1RewardsRewardIdResponse404 = {
  data: BackendError;
  status: 404;
};

export type deleteV1RewardsRewardIdResponseSuccess =
  deleteV1RewardsRewardIdResponse204 & {
    headers: Headers;
  };
export type deleteV1RewardsRewardIdResponseError = (
  | deleteV1RewardsRewardIdResponse400
  | deleteV1RewardsRewardIdResponse404
) & {
  headers: Headers;
};

export type deleteV1RewardsRewardIdResponse =
  | deleteV1RewardsRewardIdResponseSuccess
  | deleteV1RewardsRewardIdResponseError;

export const getDeleteV1RewardsRewardIdUrl = (rewardId: string) => {
  return `http://localhost:8383/v1/rewards/${rewardId}`;
};

export const deleteV1RewardsRewardId = async (
  rewardId: string,
  options?: RequestInit,
): Promise<deleteV1RewardsRewardIdResponse> => {
  const res = await fetch(getDeleteV1RewardsRewardIdUrl(rewardId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteV1RewardsRewardIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteV1RewardsRewardIdResponse;
};

export const getDeleteV1RewardsRewardIdMutationFetcher = (
  rewardId: string,
  options?: RequestInit,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteV1RewardsRewardId(rewardId, options);
  };
};
export const getDeleteV1RewardsRewardIdMutationKey = (rewardId: string) =>
  [`http://localhost:8383/v1/rewards/${rewardId}`] as const;

export type DeleteV1RewardsRewardIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteV1RewardsRewardId>>
>;

export const useDeleteV1RewardsRewardId = <TError = Promise<BackendError>>(
  rewardId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteV1RewardsRewardId>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteV1RewardsRewardId>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getDeleteV1RewardsRewardIdMutationKey(rewardId);
  const swrFn = getDeleteV1RewardsRewardIdMutationFetcher(
    rewardId,
    fetchOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type patchV1RewardsRewardIdResponse200 = {
  data: RewardSchema;
  status: 200;
};

export type patchV1RewardsRewardIdResponse400 = {
  data: BackendError;
  status: 400;
};

export type patchV1RewardsRewardIdResponse404 = {
  data: BackendError;
  status: 404;
};

export type patchV1RewardsRewardIdResponseSuccess =
  patchV1RewardsRewardIdResponse200 & {
    headers: Headers;
  };
export type patchV1RewardsRewardIdResponseError = (
  | patchV1RewardsRewardIdResponse400
  | patchV1RewardsRewardIdResponse404
) & {
  headers: Headers;
};

export type patchV1RewardsRewardIdResponse =
  | patchV1RewardsRewardIdResponseSuccess
  | patchV1RewardsRewardIdResponseError;

export const getPatchV1RewardsRewardIdUrl = (rewardId: string) => {
  return `http://localhost:8383/v1/rewards/${rewardId}`;
};

export const patchV1RewardsRewardId = async (
  rewardId: string,
  updateReward: UpdateReward,
  options?: RequestInit,
): Promise<patchV1RewardsRewardIdResponse> => {
  const res = await fetch(getPatchV1RewardsRewardIdUrl(rewardId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateReward),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchV1RewardsRewardIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchV1RewardsRewardIdResponse;
};

export const getPatchV1RewardsRewardIdMutationFetcher = (
  rewardId: string,
  options?: RequestInit,
) => {
  return (_: Key, { arg }: { arg: UpdateReward }) => {
    return patchV1RewardsRewardId(rewardId, arg, options);
  };
};
export const getPatchV1RewardsRewardIdMutationKey = (rewardId: string) =>
  [`http://localhost:8383/v1/rewards/${rewardId}`] as const;

export type PatchV1RewardsRewardIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchV1RewardsRewardId>>
>;

export const usePatchV1RewardsRewardId = <TError = Promise<BackendError>>(
  rewardId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof patchV1RewardsRewardId>>,
      TError,
      Key,
      UpdateReward,
      Awaited<ReturnType<typeof patchV1RewardsRewardId>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getPatchV1RewardsRewardIdMutationKey(rewardId);
  const swrFn = getPatchV1RewardsRewardIdMutationFetcher(
    rewardId,
    fetchOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postV1ReviewResponse201 = {
  data: PostV1Review201;
  status: 201;
};

export type postV1ReviewResponse400 = {
  data: BackendError;
  status: 400;
};

export type postV1ReviewResponse403 = {
  data: BackendError;
  status: 403;
};

export type postV1ReviewResponse404 = {
  data: BackendError;
  status: 404;
};

export type postV1ReviewResponse500 = {
  data: BackendError;
  status: 500;
};

export type postV1ReviewResponseSuccess = postV1ReviewResponse201 & {
  headers: Headers;
};
export type postV1ReviewResponseError = (
  | postV1ReviewResponse400
  | postV1ReviewResponse403
  | postV1ReviewResponse404
  | postV1ReviewResponse500
) & {
  headers: Headers;
};

export type postV1ReviewResponse =
  | postV1ReviewResponseSuccess
  | postV1ReviewResponseError;

export const getPostV1ReviewUrl = () => {
  return `http://localhost:8383/v1/review`;
};

export const postV1Review = async (
  postV1ReviewBody: PostV1ReviewBody,
  options?: RequestInit,
): Promise<postV1ReviewResponse> => {
  const res = await fetch(getPostV1ReviewUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postV1ReviewBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1ReviewResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postV1ReviewResponse;
};

export const getPostV1ReviewMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: PostV1ReviewBody }) => {
    return postV1Review(arg, options);
  };
};
export const getPostV1ReviewMutationKey = () =>
  [`http://localhost:8383/v1/review`] as const;

export type PostV1ReviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1Review>>
>;

export const usePostV1Review = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postV1Review>>,
    TError,
    Key,
    PostV1ReviewBody,
    Awaited<ReturnType<typeof postV1Review>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostV1ReviewMutationKey();
  const swrFn = getPostV1ReviewMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postV1BranchesResponse201 = {
  data: PostV1Branches201;
  status: 201;
};

export type postV1BranchesResponse409 = {
  data: BackendError;
  status: 409;
};

export type postV1BranchesResponse500 = {
  data: BackendError;
  status: 500;
};

export type postV1BranchesResponseSuccess = postV1BranchesResponse201 & {
  headers: Headers;
};
export type postV1BranchesResponseError = (
  | postV1BranchesResponse409
  | postV1BranchesResponse500
) & {
  headers: Headers;
};

export type postV1BranchesResponse =
  | postV1BranchesResponseSuccess
  | postV1BranchesResponseError;

export const getPostV1BranchesUrl = () => {
  return `http://localhost:8383/v1/branches`;
};

export const postV1Branches = async (
  createBranchDto: CreateBranchDto,
  options?: RequestInit,
): Promise<postV1BranchesResponse> => {
  const res = await fetch(getPostV1BranchesUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createBranchDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1BranchesResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postV1BranchesResponse;
};

export const getPostV1BranchesMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateBranchDto }) => {
    return postV1Branches(arg, options);
  };
};
export const getPostV1BranchesMutationKey = () =>
  [`http://localhost:8383/v1/branches`] as const;

export type PostV1BranchesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postV1Branches>>
>;

export const usePostV1Branches = <TError = Promise<BackendError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postV1Branches>>,
    TError,
    Key,
    CreateBranchDto,
    Awaited<ReturnType<typeof postV1Branches>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostV1BranchesMutationKey();
  const swrFn = getPostV1BranchesMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getV1BranchesBranchResponse200 = {
  data: GetV1BranchesBranch200;
  status: 200;
};

export type getV1BranchesBranchResponse409 = {
  data: BackendError;
  status: 409;
};

export type getV1BranchesBranchResponseSuccess =
  getV1BranchesBranchResponse200 & {
    headers: Headers;
  };
export type getV1BranchesBranchResponseError =
  getV1BranchesBranchResponse409 & {
    headers: Headers;
  };

export type getV1BranchesBranchResponse =
  | getV1BranchesBranchResponseSuccess
  | getV1BranchesBranchResponseError;

export const getGetV1BranchesBranchUrl = () => {
  return `http://localhost:8383/v1/branches/:branch`;
};

export const getV1BranchesBranch = async (
  options?: RequestInit,
): Promise<getV1BranchesBranchResponse> => {
  const res = await fetch(getGetV1BranchesBranchUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1BranchesBranchResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1BranchesBranchResponse;
};

export const getGetV1BranchesBranchKey = () =>
  [`http://localhost:8383/v1/branches/:branch`] as const;

export type GetV1BranchesBranchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1BranchesBranch>>
>;

export const useGetV1BranchesBranch = <
  TError = Promise<BackendError>,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getV1BranchesBranch>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetV1BranchesBranchKey() : null));
  const swrFn = () => getV1BranchesBranch(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
