/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const postAuthLoginBodyMethodTwoValueMin = 6;
export const postAuthLoginBodyMethodTwoValueMax = 6;

export const postAuthLoginBodyMethodTwoValueRegExp = /^[0-9]+$/;

export const PostAuthLoginBody = zod.object({
  identity: zod.string().min(1),
  method: zod.union([
    zod.object({
      type: zod.enum(["phone"]),
    }),
    zod.object({
      type: zod.enum(["code"]),
      value: zod
        .string()
        .min(postAuthLoginBodyMethodTwoValueMin)
        .max(postAuthLoginBodyMethodTwoValueMax)
        .regex(postAuthLoginBodyMethodTwoValueRegExp),
    }),
    zod.object({
      type: zod.enum(["password"]),
      value: zod.string().min(1),
    }),
  ]),
});

export const PostAuthLoginResponse = zod.union([
  zod.object({
    token: zod.string().min(1),
  }),
  zod.object({
    success: zod.literal(true),
  }),
]);

export const postAuthRegisterBodyPhoneMin = 6;

export const postAuthRegisterBodyPasswordMin = 6;

export const PostAuthRegisterBody = zod.object({
  firstName: zod.string(),
  lastName: zod.string(),
  phone: zod.string().min(postAuthRegisterBodyPhoneMin),
  email: zod.string().email().optional(),
  password: zod.string().min(postAuthRegisterBodyPasswordMin).optional(),
  role: zod.string().optional(),
});

export const GetV1UsersMeResponse = zod.object({
  id: zod.string().uuid(),
  firstName: zod.string(),
  lastName: zod.string(),
  phone: zod.string(),
  email: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  role: zod.string(),
});

export const GetV1ProductsQueryParams = zod.object({
  id: zod
    .union([
      zod.object({
        eq: zod.string().uuid(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  name: zod
    .union([
      zod.object({
        eq: zod.string(),
      }),
      zod.object({
        contains: zod.string(),
      }),
      zod.object({
        startsWith: zod.string(),
      }),
      zod.object({
        endsWith: zod.string(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  status: zod
    .union([
      zod.object({
        eq: zod.string(),
      }),
      zod.object({
        contains: zod.string(),
      }),
      zod.object({
        startsWith: zod.string(),
      }),
      zod.object({
        endsWith: zod.string(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  categoryId: zod
    .union([
      zod.object({
        eq: zod.string().uuid(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod
    .union([
      zod.object({
        eq: zod.string().datetime({}),
      }),
      zod.object({
        lt: zod.string().datetime({}),
      }),
      zod.object({
        lte: zod.string().datetime({}),
      }),
      zod.object({
        gt: zod.string().datetime({}),
      }),
      zod.object({
        gte: zod.string().datetime({}),
      }),
    ])
    .optional(),
});

export const GetV1ProductsResponse = zod.object({
  products: zod.array(
    zod.object({
      id: zod.string().uuid(),
      image: zod.string().nullable(),
      name: zod.string(),
      status: zod.string(),
      categoryId: zod.string().uuid(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const PostV1ProductsBody = zod.object({
  products: zod.array(
    zod.object({
      id: zod.string().uuid(),
      image: zod.string().nullable(),
      name: zod.string(),
      status: zod.string(),
      categoryId: zod.string().uuid(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const getV1RewardsResponseCostRegExp = /^d+$/;

export const GetV1RewardsResponseItem = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string(),
  status: zod.string(),
  cost: zod.string().regex(getV1RewardsResponseCostRegExp),
  image: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
});
export const GetV1RewardsResponse = zod.array(GetV1RewardsResponseItem);

export const GetV1RewardsHistoryResponseItem = zod.object({
  id: zod.string().uuid(),
  rewardId: zod.string().uuid(),
  userId: zod.string().uuid(),
  branchId: zod.string().uuid(),
  createdAt: zod.string().datetime({}),
});
export const GetV1RewardsHistoryResponse = zod.array(
  GetV1RewardsHistoryResponseItem,
);

export const PostV1RewardsRedeemBody = zod.object({
  rewardId: zod.string().uuid(),
  branchId: zod.string().uuid(),
});

export const postV1RewardsRedeemResponseNewBalanceRegExp = /^d+$/;

export const PostV1RewardsRedeemResponse = zod.object({
  newBalance: zod.string().regex(postV1RewardsRedeemResponseNewBalanceRegExp),
});
