/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const GetUsersMeResponse = zod.object({
  id: zod.string().uuid(),
  firstName: zod.string(),
  lastName: zod.string(),
  phone: zod.string(),
  email: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
});

export const postAuthLoginBodyMethodTwoValueMin = 6;
export const postAuthLoginBodyMethodTwoValueMax = 6;

export const postAuthLoginBodyMethodTwoValueRegExp = /^[0-9]+$/;

export const PostAuthLoginBody = zod.object({
  identity: zod.string().min(1),
  method: zod.union([
    zod.object({
      type: zod.enum(["phone"]),
    }),
    zod.object({
      type: zod.enum(["code"]),
      value: zod
        .string()
        .min(postAuthLoginBodyMethodTwoValueMin)
        .max(postAuthLoginBodyMethodTwoValueMax)
        .regex(postAuthLoginBodyMethodTwoValueRegExp),
    }),
    zod.object({
      type: zod.enum(["password"]),
      value: zod.string().min(1),
    }),
  ]),
});

export const PostAuthLoginResponse = zod.union([
  zod.object({
    token: zod.string().min(1),
  }),
  zod.object({
    success: zod.literal(true),
  }),
]);

export const postAuthRegisterBodyPhoneMin = 6;

export const postAuthRegisterBodyPasswordMin = 6;

export const PostAuthRegisterBody = zod.object({
  firstName: zod.string(),
  lastName: zod.string(),
  phone: zod.string().min(postAuthRegisterBodyPhoneMin),
  email: zod.string().email().optional(),
  password: zod.string().min(postAuthRegisterBodyPasswordMin).optional(),
  role: zod.string().optional(),
});
