/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const GetUsersMeResponse = zod.object({
  id: zod.string().uuid(),
  firstName: zod.string(),
  lastName: zod.string(),
  phone: zod.string(),
  email: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  role: zod.string().nullable(),
});

export const PostUsersUserIdRolesParams = zod.object({
  userId: zod.string().uuid(),
});

export const PostUsersUserIdRolesBody = zod.object({
  role: zod.string().min(1),
});

export const PostUsersUserIdRolesResponse = zod.object({
  userId: zod.string().uuid(),
  role: zod.string(),
});

export const DeleteUsersUserIdRolesRoleNameParams = zod.object({
  userId: zod.string().uuid(),
  roleName: zod.string(),
});

export const DeleteUsersUserIdRolesRoleNameResponse = zod.object({
  userId: zod.string().uuid(),
  role: zod.string(),
});

export const GetProductsQueryParams = zod.object({
  id: zod
    .union([
      zod.object({
        eq: zod.string().uuid(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  name: zod
    .union([
      zod.object({
        eq: zod.string(),
      }),
      zod.object({
        contains: zod.string(),
      }),
      zod.object({
        startsWith: zod.string(),
      }),
      zod.object({
        endsWith: zod.string(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  status: zod
    .union([
      zod.object({
        eq: zod.string(),
      }),
      zod.object({
        contains: zod.string(),
      }),
      zod.object({
        startsWith: zod.string(),
      }),
      zod.object({
        endsWith: zod.string(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  categoryId: zod
    .union([
      zod.object({
        eq: zod.string().uuid(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod
    .union([
      zod.object({
        eq: zod.string().datetime({}),
      }),
      zod.object({
        lt: zod.string().datetime({}),
      }),
      zod.object({
        lte: zod.string().datetime({}),
      }),
      zod.object({
        gt: zod.string().datetime({}),
      }),
      zod.object({
        gte: zod.string().datetime({}),
      }),
    ])
    .optional(),
});

export const GetProductsResponse = zod.object({
  products: zod.array(
    zod.object({
      id: zod.string().uuid(),
      image: zod.string().nullable(),
      name: zod.string(),
      status: zod.string(),
      categoryId: zod.string().uuid(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const PostProductsBody = zod.object({
  name: zod.string(),
  status: zod.string(),
  categoryId: zod.string().uuid(),
});

export const getOrdersHistoryResponseOrdersItemTotalRegExp = /^d+$/;

export const GetOrdersHistoryResponse = zod.object({
  orders: zod.array(
    zod.object({
      id: zod.string().uuid(),
      userId: zod.string().uuid(),
      branchId: zod.string().uuid(),
      discountId: zod.string().uuid(),
      total: zod.string().regex(getOrdersHistoryResponseOrdersItemTotalRegExp),
      status: zod.string(),
      note: zod.string().nullable(),
      orderNumber: zod.string(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const PatchOrdersIdCloseParams = zod.object({
  id: zod.string(),
});

export const patchOrdersIdCloseResponseTotalRegExp = /^d+$/;

export const PatchOrdersIdCloseResponse = zod.object({
  id: zod.string().uuid(),
  userId: zod.string().uuid(),
  branchId: zod.string().uuid(),
  discountId: zod.string().uuid(),
  total: zod.string().regex(patchOrdersIdCloseResponseTotalRegExp),
  status: zod.string(),
  note: zod.string().nullable(),
  orderNumber: zod.string(),
  createdAt: zod.string().datetime({}),
});

export const PatchOrdersIdReadyParams = zod.object({
  id: zod.string(),
});

export const patchOrdersIdReadyResponseTotalRegExp = /^d+$/;

export const PatchOrdersIdReadyResponse = zod.object({
  id: zod.string().uuid(),
  userId: zod.string().uuid(),
  branchId: zod.string().uuid(),
  discountId: zod.string().uuid(),
  total: zod.string().regex(patchOrdersIdReadyResponseTotalRegExp),
  status: zod.string(),
  note: zod.string().nullable(),
  orderNumber: zod.string(),
  createdAt: zod.string().datetime({}),
});

export const getOrdersIncomingResponseOrdersItemTotalRegExp = /^d+$/;

export const GetOrdersIncomingResponse = zod.object({
  orders: zod.array(
    zod.object({
      id: zod.string().uuid(),
      userId: zod.string().uuid(),
      branchId: zod.string().uuid(),
      discountId: zod.string().uuid(),
      total: zod.string().regex(getOrdersIncomingResponseOrdersItemTotalRegExp),
      status: zod.string(),
      note: zod.string().nullable(),
      orderNumber: zod.string(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const postAuthLoginBodyMethodTwoValueMin = 6;
export const postAuthLoginBodyMethodTwoValueMax = 6;

export const postAuthLoginBodyMethodTwoValueRegExp = /^[0-9]+$/;

export const PostAuthLoginBody = zod.object({
  identity: zod.string().min(1),
  method: zod.union([
    zod.object({
      type: zod.enum(["phone"]),
    }),
    zod.object({
      type: zod.enum(["code"]),
      value: zod
        .string()
        .min(postAuthLoginBodyMethodTwoValueMin)
        .max(postAuthLoginBodyMethodTwoValueMax)
        .regex(postAuthLoginBodyMethodTwoValueRegExp),
    }),
    zod.object({
      type: zod.enum(["password"]),
      value: zod.string().min(1),
    }),
  ]),
});

export const PostAuthLoginResponse = zod.union([
  zod.object({
    success: zod.literal(true),
    token: zod.string(),
    actor: zod.object({
      id: zod.string().uuid(),
      firstName: zod.string(),
      lastName: zod.string(),
      phone: zod.string(),
      email: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
      role: zod.string().nullable(),
    }),
  }),
  zod.object({
    success: zod.literal(false),
    required_action: zod.enum(["login_with_sent_code"]),
  }),
]);

export const postAuthRegisterBodyPhoneMin = 6;

export const postAuthRegisterBodyPasswordMin = 6;

export const PostAuthRegisterBody = zod.object({
  firstName: zod.string(),
  lastName: zod.string(),
  phone: zod.string().min(postAuthRegisterBodyPhoneMin),
  email: zod.string().email().optional(),
  password: zod.string().min(postAuthRegisterBodyPasswordMin).optional(),
  role: zod.string().optional(),
});

export const GetV1UsersMeResponse = zod.object({
  id: zod.string().uuid(),
  firstName: zod.string(),
  lastName: zod.string(),
  phone: zod.string(),
  email: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  role: zod.string().nullable(),
});

export const PostV1UsersUserIdRolesParams = zod.object({
  userId: zod.string().uuid(),
});

export const PostV1UsersUserIdRolesBody = zod.object({
  role: zod.string().min(1),
});

export const PostV1UsersUserIdRolesResponse = zod.object({
  userId: zod.string().uuid(),
  role: zod.string(),
});

export const DeleteV1UsersUserIdRolesRoleNameParams = zod.object({
  userId: zod.string().uuid(),
  roleName: zod.string(),
});

export const DeleteV1UsersUserIdRolesRoleNameResponse = zod.object({
  userId: zod.string().uuid(),
  role: zod.string(),
});

export const GetV1ProductsQueryParams = zod.object({
  id: zod
    .union([
      zod.object({
        eq: zod.string().uuid(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  name: zod
    .union([
      zod.object({
        eq: zod.string(),
      }),
      zod.object({
        contains: zod.string(),
      }),
      zod.object({
        startsWith: zod.string(),
      }),
      zod.object({
        endsWith: zod.string(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  status: zod
    .union([
      zod.object({
        eq: zod.string(),
      }),
      zod.object({
        contains: zod.string(),
      }),
      zod.object({
        startsWith: zod.string(),
      }),
      zod.object({
        endsWith: zod.string(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  categoryId: zod
    .union([
      zod.object({
        eq: zod.string().uuid(),
      }),
      zod.object({
        in: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod
    .union([
      zod.object({
        eq: zod.string().datetime({}),
      }),
      zod.object({
        lt: zod.string().datetime({}),
      }),
      zod.object({
        lte: zod.string().datetime({}),
      }),
      zod.object({
        gt: zod.string().datetime({}),
      }),
      zod.object({
        gte: zod.string().datetime({}),
      }),
    ])
    .optional(),
});

export const GetV1ProductsResponse = zod.object({
  products: zod.array(
    zod.object({
      id: zod.string().uuid(),
      image: zod.string().nullable(),
      name: zod.string(),
      status: zod.string(),
      categoryId: zod.string().uuid(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const PostV1ProductsBody = zod.object({
  name: zod.string(),
  status: zod.string(),
  categoryId: zod.string().uuid(),
});

export const getV1OrdersHistoryResponseOrdersItemTotalRegExp = /^d+$/;

export const GetV1OrdersHistoryResponse = zod.object({
  orders: zod.array(
    zod.object({
      id: zod.string().uuid(),
      userId: zod.string().uuid(),
      branchId: zod.string().uuid(),
      discountId: zod.string().uuid(),
      total: zod
        .string()
        .regex(getV1OrdersHistoryResponseOrdersItemTotalRegExp),
      status: zod.string(),
      note: zod.string().nullable(),
      orderNumber: zod.string(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const PatchV1OrdersIdCloseParams = zod.object({
  id: zod.string(),
});

export const patchV1OrdersIdCloseResponseTotalRegExp = /^d+$/;

export const PatchV1OrdersIdCloseResponse = zod.object({
  id: zod.string().uuid(),
  userId: zod.string().uuid(),
  branchId: zod.string().uuid(),
  discountId: zod.string().uuid(),
  total: zod.string().regex(patchV1OrdersIdCloseResponseTotalRegExp),
  status: zod.string(),
  note: zod.string().nullable(),
  orderNumber: zod.string(),
  createdAt: zod.string().datetime({}),
});

export const PatchV1OrdersIdReadyParams = zod.object({
  id: zod.string(),
});

export const patchV1OrdersIdReadyResponseTotalRegExp = /^d+$/;

export const PatchV1OrdersIdReadyResponse = zod.object({
  id: zod.string().uuid(),
  userId: zod.string().uuid(),
  branchId: zod.string().uuid(),
  discountId: zod.string().uuid(),
  total: zod.string().regex(patchV1OrdersIdReadyResponseTotalRegExp),
  status: zod.string(),
  note: zod.string().nullable(),
  orderNumber: zod.string(),
  createdAt: zod.string().datetime({}),
});

export const getV1OrdersIncomingResponseOrdersItemTotalRegExp = /^d+$/;

export const GetV1OrdersIncomingResponse = zod.object({
  orders: zod.array(
    zod.object({
      id: zod.string().uuid(),
      userId: zod.string().uuid(),
      branchId: zod.string().uuid(),
      discountId: zod.string().uuid(),
      total: zod
        .string()
        .regex(getV1OrdersIncomingResponseOrdersItemTotalRegExp),
      status: zod.string(),
      note: zod.string().nullable(),
      orderNumber: zod.string(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

export const GetV1ReportsResponse = zod.object({
  weeklyOrders: zod.array(
    zod.object({
      day: zod.string(),
      total: zod.number(),
    }),
  ),
  topProducts: zod.array(
    zod.object({
      productName: zod.string(),
      quantity: zod.number(),
    }),
  ),
  categoryConsumption: zod.array(
    zod.object({
      category: zod.string(),
      total: zod.number(),
    }),
  ),
});

export const postV1RewardsBodyCostRegExp = /^d+$/;
export const postV1RewardsBodyDiscountValueRegExp = /^d+$/;
export const postV1RewardsBodyDiscountAppliesToMin = 0;

export const PostV1RewardsBody = zod.object({
  name: zod.string().min(1),
  description: zod.string().min(1),
  status: zod.enum(["active", "inactive"]),
  cost: zod.string().regex(postV1RewardsBodyCostRegExp),
  image: zod.string().url().optional(),
  discount: zod
    .object({
      type: zod.enum(["percentage", "fixed"]),
      value: zod.string().regex(postV1RewardsBodyDiscountValueRegExp),
      appliesTo: zod
        .array(zod.string())
        .min(postV1RewardsBodyDiscountAppliesToMin),
    })
    .optional(),
});

export const getV1RewardsResponseCostRegExp = /^d+$/;
export const getV1RewardsResponseDiscountValueRegExp = /^d+$/;
export const getV1RewardsResponseDiscountMaxUsesMin = -2147483648;
export const getV1RewardsResponseDiscountMaxUsesMax = 2147483647;

export const getV1RewardsResponseDiscountCurrentUsesMin = -2147483648;
export const getV1RewardsResponseDiscountCurrentUsesMax = 2147483647;

export const GetV1RewardsResponseItem = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string(),
  status: zod.string(),
  cost: zod.string().regex(getV1RewardsResponseCostRegExp),
  discountId: zod.string().uuid(),
  image: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  deletedAt: zod.string().datetime({}).nullable(),
  discount: zod.object({
    id: zod.string().uuid(),
    name: zod.string(),
    type: zod.string(),
    value: zod.string().regex(getV1RewardsResponseDiscountValueRegExp),
    appliesTo: zod.array(zod.string()),
    state: zod.string(),
    startDate: zod.string().datetime({}),
    endDate: zod.string().datetime({}),
    code: zod.string().nullable(),
    maxUses: zod
      .number()
      .min(getV1RewardsResponseDiscountMaxUsesMin)
      .max(getV1RewardsResponseDiscountMaxUsesMax)
      .nullable(),
    currentUses: zod
      .number()
      .min(getV1RewardsResponseDiscountCurrentUsesMin)
      .max(getV1RewardsResponseDiscountCurrentUsesMax),
    isActive: zod.string().nullable(),
    hidden: zod.boolean(),
    createdAt: zod.string().datetime({}),
  }),
});
export const GetV1RewardsResponse = zod.array(GetV1RewardsResponseItem);

export const GetV1RewardsHistoryResponseItem = zod.object({
  id: zod.string().uuid(),
  rewardId: zod.string().uuid(),
  userId: zod.string().uuid(),
  branchId: zod.string().uuid(),
  createdAt: zod.string().datetime({}),
});
export const GetV1RewardsHistoryResponse = zod.array(
  GetV1RewardsHistoryResponseItem,
);

export const PostV1RewardsRedeemBody = zod.object({
  rewardId: zod.string().uuid(),
  branchId: zod.string().uuid(),
});

export const postV1RewardsRedeemResponseNewBalanceRegExp = /^d+$/;

export const PostV1RewardsRedeemResponse = zod.object({
  newBalance: zod.string().regex(postV1RewardsRedeemResponseNewBalanceRegExp),
});

export const DeleteV1RewardsRewardIdParams = zod.object({
  rewardId: zod.string().uuid(),
});

export const PatchV1RewardsRewardIdParams = zod.object({
  rewardId: zod.string().uuid(),
});

export const patchV1RewardsRewardIdBodyCostRegExp = /^d+$/;

export const PatchV1RewardsRewardIdBody = zod.object({
  name: zod.string().min(1).optional(),
  description: zod.string().min(1).optional(),
  status: zod.enum(["active", "inactive"]).optional(),
  cost: zod.string().regex(patchV1RewardsRewardIdBodyCostRegExp).optional(),
  image: zod.string().url().optional(),
});

export const patchV1RewardsRewardIdResponseCostRegExp = /^d+$/;
export const patchV1RewardsRewardIdResponseDiscountValueRegExp = /^d+$/;
export const patchV1RewardsRewardIdResponseDiscountMaxUsesMin = -2147483648;
export const patchV1RewardsRewardIdResponseDiscountMaxUsesMax = 2147483647;

export const patchV1RewardsRewardIdResponseDiscountCurrentUsesMin = -2147483648;
export const patchV1RewardsRewardIdResponseDiscountCurrentUsesMax = 2147483647;

export const PatchV1RewardsRewardIdResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string(),
  status: zod.string(),
  cost: zod.string().regex(patchV1RewardsRewardIdResponseCostRegExp),
  discountId: zod.string().uuid(),
  image: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  deletedAt: zod.string().datetime({}).nullable(),
  discount: zod.object({
    id: zod.string().uuid(),
    name: zod.string(),
    type: zod.string(),
    value: zod
      .string()
      .regex(patchV1RewardsRewardIdResponseDiscountValueRegExp),
    appliesTo: zod.array(zod.string()),
    state: zod.string(),
    startDate: zod.string().datetime({}),
    endDate: zod.string().datetime({}),
    code: zod.string().nullable(),
    maxUses: zod
      .number()
      .min(patchV1RewardsRewardIdResponseDiscountMaxUsesMin)
      .max(patchV1RewardsRewardIdResponseDiscountMaxUsesMax)
      .nullable(),
    currentUses: zod
      .number()
      .min(patchV1RewardsRewardIdResponseDiscountCurrentUsesMin)
      .max(patchV1RewardsRewardIdResponseDiscountCurrentUsesMax),
    isActive: zod.string().nullable(),
    hidden: zod.boolean(),
    createdAt: zod.string().datetime({}),
  }),
});

export const postV1ReviewBodySatisfactionRateMin = 0;
export const postV1ReviewBodySatisfactionRateMax = 5;

export const PostV1ReviewBody = zod.object({
  orderId: zod.string().uuid(),
  userId: zod.string().uuid(),
  branchId: zod.string().uuid(),
  satisfactionRate: zod
    .number()
    .min(postV1ReviewBodySatisfactionRateMin)
    .max(postV1ReviewBodySatisfactionRateMax),
  notes: zod.string().optional(),
});

export const PostV1BranchesBody = zod.object({
  name: zod.string(),
  state: zod.string(),
});

export const GetV1BranchesBranchResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  state: zod.string(),
  createdAt: zod.string().datetime({}),
});
