/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type CreateRewardStatus =
  (typeof CreateRewardStatus)[keyof typeof CreateRewardStatus];

export const CreateRewardStatus = {
  active: "active",
  inactive: "inactive",
} as const;
