/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRewardDiscountType } from "./createRewardDiscountType";

export type CreateRewardDiscount = {
  type: CreateRewardDiscountType;
  /** @pattern ^d+$ */
  value: string;
  /** @minItems 0 */
  appliesTo: string[];
};
