/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRewardDiscount } from "./createRewardDiscount";
import type { CreateRewardStatus } from "./createRewardStatus";

export interface CreateReward {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  status: CreateRewardStatus;
  /** @pattern ^d+$ */
  cost: string;
  image?: string;
  discount?: CreateRewardDiscount;
}
