/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface Error {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  message: string;
}
