/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1Branches200Item = {
  id: string;
  name: string;
  state: string;
  createdAt: string;
};
