/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1Reports200CategoryConsumptionItem } from "./getV1Reports200CategoryConsumptionItem";
import type { GetV1Reports200TopProductsItem } from "./getV1Reports200TopProductsItem";
import type { GetV1Reports200WeeklyOrdersItem } from "./getV1Reports200WeeklyOrdersItem";

export type GetV1Reports200 = {
  weeklyOrders: GetV1Reports200WeeklyOrdersItem[];
  topProducts: GetV1Reports200TopProductsItem[];
  categoryConsumption: GetV1Reports200CategoryConsumptionItem[];
};
