/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1ProductsParams = {
  id?:
    | {
        eq: string;
      }
    | {
        in: string;
      };
  name?:
    | {
        eq: string;
      }
    | {
        contains: string;
      }
    | {
        startsWith: string;
      }
    | {
        endsWith: string;
      }
    | {
        in: string;
      };
  status?:
    | {
        eq: string;
      }
    | {
        contains: string;
      }
    | {
        startsWith: string;
      }
    | {
        endsWith: string;
      }
    | {
        in: string;
      };
  categoryId?:
    | {
        eq: string;
      }
    | {
        in: string;
      };
  createdAt?:
    | {
        eq: string;
      }
    | {
        lt: string;
      }
    | {
        lte: string;
      }
    | {
        gt: string;
      }
    | {
        gte: string;
      };
};
