/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1Rewards200Item = {
  id: string;
  name: string;
  description: string;
  status: string;
  /** @pattern ^d+$ */
  cost: string;
  /** @nullable */
  image: string | null;
  createdAt: string;
};
