/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { IncomingOrdersOrdersItem } from "./incomingOrdersOrdersItem";

export interface IncomingOrders {
  orders: IncomingOrdersOrdersItem[];
}
