/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { Actor } from "./actor";

export type LoginResult =
  | {
      success: boolean;
      token: string;
      actor: Actor;
    }
  | {
      success: boolean;
      required_action: "login_with_sent_code";
    };
