/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type LoginMethod =
  | {
      type: "phone";
    }
  | {
      type: "code";
      /**
       * @minLength 6
       * @maxLength 6
       * @pattern ^[0-9]+$
       */
      value: string;
    }
  | {
      type: "password";
      /** @minLength 1 */
      value: string;
    };
