/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type PatchOrdersIdClose200 = {
  id: string;
  userId: string;
  branchId: string;
  discountId: string;
  /** @pattern ^d+$ */
  total: string;
  status: string;
  /** @nullable */
  note: string | null;
  orderNumber: string;
  createdAt: string;
};
