/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type PostV1ProductsBody = {
  name: string;
  status: string;
  categoryId: string;
};
