/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLoginBodyMethod } from "./postAuthLoginBodyMethod";

export type PostAuthLoginBody = {
  /** @minLength 1 */
  identity: string;
  method: PostAuthLoginBodyMethod;
};
