/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type PostV1Review201 = {
  id: string;
  orderId: string;
  userId: string;
  branchId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  satisfactionRate: number;
  /** @nullable */
  notes: string | null;
  createdAt: string;
};
