/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type PostV1ReviewBody = {
  orderId: string;
  userId: string;
  branchId: string;
  /**
   * @minimum 0
   * @maximum 5
   */
  satisfactionRate: number;
  notes?: string;
};
