/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthRegisterBody = {
  firstName: string;
  lastName: string;
  /** @minLength 6 */
  phone: string;
  email?: string;
  /** @minLength 6 */
  password?: string;
  role?: string;
};
