/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type ProductListProductsItem = {
  id: string;
  /** @nullable */
  image: string | null;
  name: string;
  status: string;
  categoryId: string;
  createdAt: string;
};
