/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type RewardSchemaDiscount = {
  id: string;
  name: string;
  type: string;
  /** @pattern ^d+$ */
  value: string;
  appliesTo: string[];
  state: string;
  startDate: string;
  endDate: string;
  /** @nullable */
  code: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  maxUses: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  currentUses: number;
  /** @nullable */
  isActive: string | null;
  hidden: boolean;
  createdAt: string;
};
