/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type Token =
  | {
      /** @minLength 1 */
      token: string;
    }
  | {
      success: boolean;
    };
