/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRewardStatus } from "./updateRewardStatus";

export interface UpdateReward {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  description?: string;
  status?: UpdateRewardStatus;
  /** @pattern ^d+$ */
  cost?: string;
  image?: string;
}
