/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateRewardStatus =
  (typeof UpdateRewardStatus)[keyof typeof UpdateRewardStatus];

export const UpdateRewardStatus = {
  active: "active",
  inactive: "inactive",
} as const;
