/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Maree Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  phone: string;
  /** @nullable */
  email: string | null;
  createdAt: string;
}
