/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminOrderRouteImport } from './routes/admin/order'
import { Route as AdminBranchesRouteImport } from './routes/admin/branches'
import { Route as ClientMenuRouteImport } from './routes/_client/menu'
import { Route as ClientLoyaltyRouteImport } from './routes/_client/loyalty'
import { Route as ClientCartRouteImport } from './routes/_client/cart'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminStaffIndexRouteImport } from './routes/admin/staff/index'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as AdminStaffIdRouteImport } from './routes/admin/staff/$id'
import { Route as AdminBranchesBranchIdRouteImport } from './routes/admin/branches/$branchId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrderRoute = AdminOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ClientMenuRoute = ClientMenuRouteImport.update({
  id: '/_client/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoyaltyRoute = ClientLoyaltyRouteImport.update({
  id: '/_client/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCartRoute = ClientCartRouteImport.update({
  id: '/_client/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIdRoute = AdminStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBranchesBranchIdRoute = AdminBranchesBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => AdminBranchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/cart': typeof ClientCartRoute
  '/loyalty': typeof ClientLoyaltyRoute
  '/menu': typeof ClientMenuRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/order': typeof AdminOrderRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/cart': typeof ClientCartRoute
  '/loyalty': typeof ClientLoyaltyRoute
  '/menu': typeof ClientMenuRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/order': typeof AdminOrderRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_client/cart': typeof ClientCartRoute
  '/_client/loyalty': typeof ClientLoyaltyRoute
  '/_client/menu': typeof ClientMenuRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/order': typeof AdminOrderRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/cart'
    | '/loyalty'
    | '/menu'
    | '/admin/branches'
    | '/admin/order'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/'
    | '/admin/branches/$branchId'
    | '/admin/staff/$id'
    | '/admin/users/$id'
    | '/admin/staff/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/cart'
    | '/loyalty'
    | '/menu'
    | '/admin/branches'
    | '/admin/order'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin'
    | '/admin/branches/$branchId'
    | '/admin/staff/$id'
    | '/admin/users/$id'
    | '/admin/staff'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/_client/cart'
    | '/_client/loyalty'
    | '/_client/menu'
    | '/admin/branches'
    | '/admin/order'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/'
    | '/admin/branches/$branchId'
    | '/admin/staff/$id'
    | '/admin/users/$id'
    | '/admin/staff/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ClientCartRoute: typeof ClientCartRoute
  ClientLoyaltyRoute: typeof ClientLoyaltyRoute
  ClientMenuRoute: typeof ClientMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/order': {
      id: '/admin/order'
      path: '/order'
      fullPath: '/admin/order'
      preLoaderRoute: typeof AdminOrderRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_client/menu': {
      id: '/_client/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof ClientMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/loyalty': {
      id: '/_client/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof ClientLoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/cart': {
      id: '/_client/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ClientCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/$id': {
      id: '/admin/staff/$id'
      path: '/staff/$id'
      fullPath: '/admin/staff/$id'
      preLoaderRoute: typeof AdminStaffIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/branches/$branchId': {
      id: '/admin/branches/$branchId'
      path: '/$branchId'
      fullPath: '/admin/branches/$branchId'
      preLoaderRoute: typeof AdminBranchesBranchIdRouteImport
      parentRoute: typeof AdminBranchesRoute
    }
  }
}

interface AdminBranchesRouteChildren {
  AdminBranchesBranchIdRoute: typeof AdminBranchesBranchIdRoute
}

const AdminBranchesRouteChildren: AdminBranchesRouteChildren = {
  AdminBranchesBranchIdRoute: AdminBranchesBranchIdRoute,
}

const AdminBranchesRouteWithChildren = AdminBranchesRoute._addFileChildren(
  AdminBranchesRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBranchesRoute: typeof AdminBranchesRouteWithChildren
  AdminOrderRoute: typeof AdminOrderRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStaffIdRoute: typeof AdminStaffIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBranchesRoute: AdminBranchesRouteWithChildren,
  AdminOrderRoute: AdminOrderRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStaffIdRoute: AdminStaffIdRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ClientCartRoute: ClientCartRoute,
  ClientLoyaltyRoute: ClientLoyaltyRoute,
  ClientMenuRoute: ClientMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
