/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminOrderRouteImport } from './routes/admin/order'
import { Route as AdminCreateProductRouteImport } from './routes/admin/create-product'
import { Route as ClientReviewRouteImport } from './routes/_client/review'
import { Route as ClientMenuRouteImport } from './routes/_client/menu'
import { Route as ClientLoyaltyRouteImport } from './routes/_client/loyalty'
import { Route as ClientCustomizeProductRouteImport } from './routes/_client/customize-product'
import { Route as ClientCartRouteImport } from './routes/_client/cart'
import { Route as AdminInventoryRouteRouteImport } from './routes/admin/inventory/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminStaffIndexRouteImport } from './routes/admin/staff/index'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts/index'
import { Route as AdminBranchesIndexRouteImport } from './routes/admin/branches/index'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as AdminStaffIdRouteImport } from './routes/admin/staff/$id'
import { Route as AdminInventoryProductsRouteImport } from './routes/admin/inventory/products'
import { Route as AdminInventoryCategoriesRouteImport } from './routes/admin/inventory/categories'
import { Route as AdminDiscountsIdRouteImport } from './routes/admin/discounts/$id'
import { Route as AdminBranchesBranchIdRouteImport } from './routes/admin/branches/$branchId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrderRoute = AdminOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreateProductRoute = AdminCreateProductRouteImport.update({
  id: '/create-product',
  path: '/create-product',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ClientReviewRoute = ClientReviewRouteImport.update({
  id: '/_client/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMenuRoute = ClientMenuRouteImport.update({
  id: '/_client/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoyaltyRoute = ClientLoyaltyRouteImport.update({
  id: '/_client/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCustomizeProductRoute = ClientCustomizeProductRouteImport.update({
  id: '/_client/customize-product',
  path: '/customize-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCartRoute = ClientCartRouteImport.update({
  id: '/_client/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRouteRoute = AdminInventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBranchesIndexRoute = AdminBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIdRoute = AdminStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryProductsRoute = AdminInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminInventoryRouteRoute,
} as any)
const AdminInventoryCategoriesRoute =
  AdminInventoryCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminInventoryRouteRoute,
  } as any)
const AdminDiscountsIdRoute = AdminDiscountsIdRouteImport.update({
  id: '/discounts/$id',
  path: '/discounts/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBranchesBranchIdRoute = AdminBranchesBranchIdRouteImport.update({
  id: '/branches/$branchId',
  path: '/branches/$branchId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/inventory': typeof AdminInventoryRouteRouteWithChildren
  '/cart': typeof ClientCartRoute
  '/customize-product': typeof ClientCustomizeProductRoute
  '/loyalty': typeof ClientLoyaltyRoute
  '/menu': typeof ClientMenuRoute
  '/review': typeof ClientReviewRoute
  '/admin/create-product': typeof AdminCreateProductRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/discounts/$id': typeof AdminDiscountsIdRoute
  '/admin/inventory/categories': typeof AdminInventoryCategoriesRoute
  '/admin/inventory/products': typeof AdminInventoryProductsRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/branches/': typeof AdminBranchesIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/inventory': typeof AdminInventoryRouteRouteWithChildren
  '/cart': typeof ClientCartRoute
  '/customize-product': typeof ClientCustomizeProductRoute
  '/loyalty': typeof ClientLoyaltyRoute
  '/menu': typeof ClientMenuRoute
  '/review': typeof ClientReviewRoute
  '/admin/create-product': typeof AdminCreateProductRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/discounts/$id': typeof AdminDiscountsIdRoute
  '/admin/inventory/categories': typeof AdminInventoryCategoriesRoute
  '/admin/inventory/products': typeof AdminInventoryProductsRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/branches': typeof AdminBranchesIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/inventory': typeof AdminInventoryRouteRouteWithChildren
  '/_client/cart': typeof ClientCartRoute
  '/_client/customize-product': typeof ClientCustomizeProductRoute
  '/_client/loyalty': typeof ClientLoyaltyRoute
  '/_client/menu': typeof ClientMenuRoute
  '/_client/review': typeof ClientReviewRoute
  '/admin/create-product': typeof AdminCreateProductRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/branches/$branchId': typeof AdminBranchesBranchIdRoute
  '/admin/discounts/$id': typeof AdminDiscountsIdRoute
  '/admin/inventory/categories': typeof AdminInventoryCategoriesRoute
  '/admin/inventory/products': typeof AdminInventoryProductsRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/branches/': typeof AdminBranchesIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/admin/inventory'
    | '/cart'
    | '/customize-product'
    | '/loyalty'
    | '/menu'
    | '/review'
    | '/admin/create-product'
    | '/admin/order'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/'
    | '/admin/branches/$branchId'
    | '/admin/discounts/$id'
    | '/admin/inventory/categories'
    | '/admin/inventory/products'
    | '/admin/staff/$id'
    | '/admin/users/$id'
    | '/admin/branches/'
    | '/admin/discounts/'
    | '/admin/staff/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/admin/inventory'
    | '/cart'
    | '/customize-product'
    | '/loyalty'
    | '/menu'
    | '/review'
    | '/admin/create-product'
    | '/admin/order'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin'
    | '/admin/branches/$branchId'
    | '/admin/discounts/$id'
    | '/admin/inventory/categories'
    | '/admin/inventory/products'
    | '/admin/staff/$id'
    | '/admin/users/$id'
    | '/admin/branches'
    | '/admin/discounts'
    | '/admin/staff'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/admin/inventory'
    | '/_client/cart'
    | '/_client/customize-product'
    | '/_client/loyalty'
    | '/_client/menu'
    | '/_client/review'
    | '/admin/create-product'
    | '/admin/order'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/'
    | '/admin/branches/$branchId'
    | '/admin/discounts/$id'
    | '/admin/inventory/categories'
    | '/admin/inventory/products'
    | '/admin/staff/$id'
    | '/admin/users/$id'
    | '/admin/branches/'
    | '/admin/discounts/'
    | '/admin/staff/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ClientCartRoute: typeof ClientCartRoute
  ClientCustomizeProductRoute: typeof ClientCustomizeProductRoute
  ClientLoyaltyRoute: typeof ClientLoyaltyRoute
  ClientMenuRoute: typeof ClientMenuRoute
  ClientReviewRoute: typeof ClientReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/order': {
      id: '/admin/order'
      path: '/order'
      fullPath: '/admin/order'
      preLoaderRoute: typeof AdminOrderRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/create-product': {
      id: '/admin/create-product'
      path: '/create-product'
      fullPath: '/admin/create-product'
      preLoaderRoute: typeof AdminCreateProductRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_client/review': {
      id: '/_client/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ClientReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/menu': {
      id: '/_client/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof ClientMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/loyalty': {
      id: '/_client/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof ClientLoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/customize-product': {
      id: '/_client/customize-product'
      path: '/customize-product'
      fullPath: '/customize-product'
      preLoaderRoute: typeof ClientCustomizeProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/cart': {
      id: '/_client/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ClientCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/branches/': {
      id: '/admin/branches/'
      path: '/branches'
      fullPath: '/admin/branches/'
      preLoaderRoute: typeof AdminBranchesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/$id': {
      id: '/admin/staff/$id'
      path: '/staff/$id'
      fullPath: '/admin/staff/$id'
      preLoaderRoute: typeof AdminStaffIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/products': {
      id: '/admin/inventory/products'
      path: '/products'
      fullPath: '/admin/inventory/products'
      preLoaderRoute: typeof AdminInventoryProductsRouteImport
      parentRoute: typeof AdminInventoryRouteRoute
    }
    '/admin/inventory/categories': {
      id: '/admin/inventory/categories'
      path: '/categories'
      fullPath: '/admin/inventory/categories'
      preLoaderRoute: typeof AdminInventoryCategoriesRouteImport
      parentRoute: typeof AdminInventoryRouteRoute
    }
    '/admin/discounts/$id': {
      id: '/admin/discounts/$id'
      path: '/discounts/$id'
      fullPath: '/admin/discounts/$id'
      preLoaderRoute: typeof AdminDiscountsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/branches/$branchId': {
      id: '/admin/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/admin/branches/$branchId'
      preLoaderRoute: typeof AdminBranchesBranchIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminInventoryRouteRouteChildren {
  AdminInventoryCategoriesRoute: typeof AdminInventoryCategoriesRoute
  AdminInventoryProductsRoute: typeof AdminInventoryProductsRoute
}

const AdminInventoryRouteRouteChildren: AdminInventoryRouteRouteChildren = {
  AdminInventoryCategoriesRoute: AdminInventoryCategoriesRoute,
  AdminInventoryProductsRoute: AdminInventoryProductsRoute,
}

const AdminInventoryRouteRouteWithChildren =
  AdminInventoryRouteRoute._addFileChildren(AdminInventoryRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminInventoryRouteRoute: typeof AdminInventoryRouteRouteWithChildren
  AdminCreateProductRoute: typeof AdminCreateProductRoute
  AdminOrderRoute: typeof AdminOrderRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBranchesBranchIdRoute: typeof AdminBranchesBranchIdRoute
  AdminDiscountsIdRoute: typeof AdminDiscountsIdRoute
  AdminStaffIdRoute: typeof AdminStaffIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminBranchesIndexRoute: typeof AdminBranchesIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminInventoryRouteRoute: AdminInventoryRouteRouteWithChildren,
  AdminCreateProductRoute: AdminCreateProductRoute,
  AdminOrderRoute: AdminOrderRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBranchesBranchIdRoute: AdminBranchesBranchIdRoute,
  AdminDiscountsIdRoute: AdminDiscountsIdRoute,
  AdminStaffIdRoute: AdminStaffIdRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminBranchesIndexRoute: AdminBranchesIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ClientCartRoute: ClientCartRoute,
  ClientCustomizeProductRoute: ClientCustomizeProductRoute,
  ClientLoyaltyRoute: ClientLoyaltyRoute,
  ClientMenuRoute: ClientMenuRoute,
  ClientReviewRoute: ClientReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
